No libstdc++ for GCN
Like commit d94fae044da071381b73a2ee8afa874b14fa3820 "No libstdc++ for nvptx"
(2015) and elsewhere.

Based on commit 5f1bed2a7af828103ca23a3546466a23e8dd2f30 (2023-12-16), there
are a ton of progressions (for test cases not actually depending on libstdc++
symbols, obviously):

                    === g++ Summary ===

    # of expected passes            [-178369-]{+189226+}
    # of unexpected failures        [-19880-]{+14089+}
    # of unexpected successes       14
    # of expected failures          [-1684-]{+1685+}
    # of unresolved testcases       [-9820-]{+4837+}
    # of unsupported tests          [-11971-]{+11968+}

..., and only two benign "regressions":

    [-UNSUPPORTED:-]{+FAIL:+} g++.dg/init/array54.C  -std=c++14 {+(test for excess errors)+}
    {+UNRESOLVED: g++.dg/init/array54.C  -std=c++14 compilation failed to produce executable+}
    [Etc.]

    [...]/g++.dg/init/array54.C:5:10: fatal error: atomic: No such file or directory

That's similar to a lof of other test cases intending to '#include' standard
C++/libstdc++ headers; to be addressed in due time.

    PASS: g++.old-deja/g++.pt/const2.C  -std=c++98  at line 5 (test for warnings, line )
    [-PASS:-]{+FAIL:+} g++.old-deja/g++.pt/const2.C  -std=c++98 (test for excess errors)
    [Etc.]

    ld: error: undefined symbol: A<int>::i
    >>> referenced by /tmp/ccqXWCSh.o:(p)

The 'error: undefined symbol' is expected here; maybe should simply in the test
case 'dg-prune-output "referenced by"'?  (This PASSed before, as the
'dg-message "i"' was satisfied by 'ld: error: unable to find library -lstdc++',
eh...)

	gcc/
	* config/gcn/gcn.h (LIBSTDCXX): Define to "gcc".