c++: provide #include hint for missing includes [PR110164]
> On Fri, 2023-06-23 at 12:08 -0400, Jason Merrill wrote:
> > On 6/22/23 11:50, Marek Polacek wrote:
> > > On Wed, Jun 21, 2023 at 04:44:00PM -0400, David Malcolm via Gcc-patches wrote:
> > > I'd like to ping this C++ FE patch for review:
> > > https://gcc.gnu.org/pipermail/gcc-patches/2023-June/621779.html

> > Not an approval, but LGTM, though some nits below:

> OK with the tweaks Marek suggests.

Thanks Marek and Jason.

For reference, here's what I pushed (as r14-2055-g13709b518aa976):

PR c++/110164 notes that in cases where we have a forward decl
of a std library type such as:

std::array<int, 10> x;

we emit this diagnostic:

error: aggregate ‘std::array<int, 10> x’ has incomplete type and cannot be defined

This patch adds this hint to the diagnostic:

note: ‘std::array’ is defined in header ‘<array>’; this is probably fixable by adding ‘#include <array>’

gcc/cp/ChangeLog:
	PR c++/110164
	* cp-name-hint.h (maybe_suggest_missing_header): New decl.
	* decl.cc: Define INCLUDE_MEMORY.  Add include of
	"cp/cp-name-hint.h".
	(start_decl_1): Call maybe_suggest_missing_header.
	* name-lookup.cc (maybe_suggest_missing_header): Remove "static".

gcc/testsuite/ChangeLog:
	PR c++/110164
	* g++.dg/diagnostic/missing-header-pr110164.C: New test.