c++: constexpr error with defaulted virtual dtor [PR93413]
We're rejecting the below testcase with

  error: 'virtual constexpr Base::~Base()' used before its definition
  error: 'virtual constexpr Derived::~Derived()' used before its definition

due to an early exit added to mark_used by r181272 to defer synthesis of
virtual destructors until EOF where we can set their linkage.  This makes
them effectively unusable for constexpr evaluation since that needs to
be done immediately and can't also be deferred.

Fortunately, this early exit seems to no longer be necessary ever since
r208030 enabled us to tentatively set linkage of all defaulted virtual
destructors, including templated ones.  So this patch just gets rid of
this early exit.

Bootstrapped and regtested on x86_64-pc-linux-gnu, does this look OK for
trunk?

	PR c++/93413

gcc/cp/ChangeLog:

	* decl2.cc (mark_used): Don't defer synthesis of virtual
	functions.

gcc/testsuite/ChangeLog:

	* g++.dg/cpp2a/constexpr-virtual21.C: New test.