RISC-V: Fix ICE && codegen error of scalar move in RV32 system.
bug.C:144:2: error: unrecognizable insn:
  144 |  }
      |  ^
(insn 684 683 685 26 (set (reg:SI 513)
        (and:SI (const_int 4 [0x4])
            (const_int 1 [0x1]))) "bug.C":115:47 -1
     (nil))

andi a4,a4,1 ===> sgtu a4,a4,zero
vsetlvi tu        vsetvli tu
vlse              vlse

gcc/ChangeLog:

        * config/riscv/riscv-protos.h (gen_avl_for_scalar_move): New function.
        * config/riscv/riscv-v.cc (gen_avl_for_scalar_move): New function.
        * config/riscv/vector.md: Fix scalar move bug.

gcc/testsuite/ChangeLog:

        * gcc.target/riscv/rvv/base/scalar_move-6.c: Adapt test.
        * gcc.target/riscv/rvv/base/scalar_move-9.c: New test.