OpenMP: Improve C/C++ parsing error message [PR109999]
I stumbled over that error message the other day and found it a bit
confusing:

   error: expected ‘#pragma omp’ clause before ‘uses_allocators’

The new wording is not the best, but I think at least better:

   error: expected an OpenMP clause before ‘uses_allocators’

('uses_allocators' is a valid OpenMP 5.x clause but not yet handled in GCC;
There is a patch that implements the support but some review-requested
changes are still required before it can be merged.)

Committed as r14-1404-ga899401404186843f38462c8fc9de733f19ce864

Tobias

PS: Jakub did wonder about the translatability of "expect ..." + "<before ...>",
but it is a preexisting issue – and the commit makes it neither worse
nor better than before.
-----------------
Siemens Electronic Design Automation GmbH; Anschrift: Arnulfstraße 201, 80634 München; Gesellschaft mit beschränkter Haftung; Geschäftsführer: Thomas Heurung, Frank Thürauf; Sitz der Gesellschaft: München; Registergericht München, HRB 106955

commit a899401404186843f38462c8fc9de733f19ce864
Author: Tobias Burnus <tobias@codesourcery.com>
Date:   Tue May 30 12:49:09 2023 +0200

    OpenMP: Improve C/C++ parsing error message [PR109999]

    Replace
      error: expected '#pragma omp' clause before ...
    by the the more readable/clearer
      error: expected an OpenMP clause before ...

    (And likewise for '#pragma acc' and OpenACC.)

            PR c/109999

    gcc/c/ChangeLog:

            * c-parser.cc (c_parser_oacc_all_clauses,
            c_parser_omp_all_clauses): Improve error wording.

    gcc/cp/ChangeLog:

            * parser.cc (cp_parser_oacc_all_clauses,
            cp_parser_omp_all_clauses): Improve error wording.

    gcc/testsuite/ChangeLog:

            * c-c++-common/goacc/asyncwait-1.c: Update dg-error.
            * c-c++-common/goacc/clauses-fail.c: Likewise.
            * c-c++-common/goacc/data-2.c: Likewise.
            * c-c++-common/gomp/declare-target-2.c: Likewise.
            * c-c++-common/gomp/directive-1.c: Likewise.
            * g++.dg/goacc/data-1.C: Likewise.